johnsons53/CSC-450-Group-4

- iepHome.html
- style.css
Begin to build website files by creating & adding early-stage dashboard/home page HTML and CSS stylesheet
> Add dashboard HTML file and stylesheet

- iepProviderObjectiveForm.html
- style.css
Created form for provider to add or update an objective.
Added rule to stylesheet for navigation links. Styling for links with class "navigation" to look like buttons.
> Add iepProviderObjectiveForm.html

- iepProviderObjectiveForm.html
- iepProviderReportForm.html
Made correction in comments of Objective Form.
Created Provider Report Form html.
> Add iepProviderReportForm.html

- iepHome.html
- style.css
First upload of home.html and style.css were unsuccessful. Files fixed and uploaded in full.
> Update Home and Style Files

- iepProviderReportForm.php
Basic PHP form handling added to Provider Report form
> Add PHP form handling to Report form

- iepDetailView.js
- iepParentHome.php
- iepProviderGoalForm.php
- iepProviderObjectiveForm.php
- iepProviderReportForm.php
Add show/hide JavaScript to parent dashboard.
Removed unnecessary form validation from goal, objective forms.
> Parent Home JS, minor changes to forms

-  login.php
login.php page for connecting to the database from various pages. You will need to put in username/password in the file.
See comments for code to include on other pages to login to database.
> Create  login.php

-  login.php
- databaseConnectionTestPage.php
- iepParentHome.php
Work on connection to database from PHP pages.
My initial solution was outdated, so I had to do some further research into connecting to the database.
However, I was able to get a connection to work.
Changes:  login.php now returns an array containing the login credentials for the database. The comments contain a section of PHP code to establish a connection to the database from another page.
Removed first attempt at adding connection from parent dashboard.
databaseConnectionTestPage.php added to test and demo connection steps.
> Connection to MySQL database from pages

- classes.php
- databaseConnectionTestPage.php
- iepDetailView.js
Query testing on test page. Worked on putting data into arrays from mysqli result object.
Added classes.php page for class definitions. This is still in progress, but I wanted to make it easy for everyone to find for this evening.
Disabled leftover testing alerts in iepDetailView.js
> Sql query testing

- databaseConnectionTestPage.php
- login.php
Testing  alternative way to store file path for more consistent results.
Uncovered mistake in file name: " login.php" instead of "login.php".
> Testing login.php connection issues

- iepMessage.html
- style.css
Create message view HTML
Edit style.css - add message settings
> Create message view

- iepLogin.php
Added switch to iepLogin.php that is based off of user's user type when logging in. Switch creates object of user type, serializes and then sets current user to it. Once log in is complete then goes to iepDashboard.php.
> Added Switch to iepLogin.php 

- Goal.php
- Guardian.php
- Objective.php
- Student.php
- User.php
- databaseConnectionTestPage.php
- deleteGoal.php
- functions.php
- iepDashboard.php
- iepDetailView.js
- iepProviderGoalForm.php
- iepProviderObjectiveForm.php
- iepProviderReportForm.php
- mainContent.php
- reportMeter.php
Changes to iepDashboard. 
Toggle between student content with tab buttons in left nav bar.
Provider users have buttons to link to form pages for updating student data in the database.
Users can select a report to view by date, updating the report meter.
Delete button handling is still in progress.
Added button to link to documents page.
> Provider buttons

- iepLogin.css
- iepLogin.php
- iepSettings.php
Also added a new CSS for the lepLogin.php page
> Updated iepSettings.php and added User Interface to iepLogin and iepSettings

- iepDocument.php
- iep_portal_v04_document.sql
- login.php
Locate documents and display in list format to page. New database file added with document table updated
> Added Document php page

- iepLogin.php
- iepSettings.php
Added new connection to iepSettinsg.php and switched header in iepLogin to iepDashboard
> iepSettingsConnectionAdded

- Document.php
- Student.php
Changes to Document and Student class to match updated document table.
> Adjust Document class to new db table

- iepDocument.php
Document page add/remove document functionality added. Ability to add/remove file to/from both database and a localhost folder called "documents". 
Will need updating for server functionality.
> Document crud operations

- iepDocument.php
File uploads collect current datetime timestamp and insert into database with documents. Display sorted by descending date.
> Update file with current date

- iepDashboard.php
- iepDocument.php
- iepMessage.html
- iepSettings.php
- mainContent.php
Document, Settings and Messages links now open in separate new pages. 
Implemented functional Horizontal Nav bar on each of these pages, all links work except Logout.
Settings page loads with appropriate data (logged in user or access by Admin dashboard)
> Documents settings messages navigation

- iepDashboard.php
- iepDocument.php
- iepMessage.html
- iepSettings.php
- iepUserLogout.php
Added iepUserLogout.php, and updated links on all nav bars.
> Added Logout functionality

- adminSettings.php
- fetch.php
- insert.php
- select.php
Admin settings view to update other user's information. Utilizes modals, javascript, and bootstrap to retrieve and update user information along with fetch.php, select.php, and insert.php.
> Created adminSettings.php

- adminInsert.php
- adminSettings.php
- userInsert.php
- userSettings.php
- The userSettings.php and adminSettings.php pages are functional
- Added more fields to be able to change, like user_first_name, user_last_name, user_password, to adminSettings.php
- Updated both insert pages to allow functionality
> userSettings.php and adminSettings.php pages are functional

- footer.php
- iepDashboard.php
- iepDocument.php
- mainContent.php
- reportMeter.php
- style.css
- userSettings.php
Added footer with project information
Adjusted data display on dashboard, userSettings
> Add Footer to pages

- goalForm.php
- iepDashboard.php
- mainContent.php
- objectiveForm.php
- reportMeter.php
- style.css
- userSettings.php
Changes to forms to meet accessibility standards.
Show/Hide buttons changed.
Fixed orphaned labels on forms.
Added fieldset for radio buttons.
Fixed contrast error on message badge.
Added lang attribute on userSettings page.
Removed old versions of buttons and links.
> Form accessibility fixes

- adminSettings.php
- iepLogin.php
- When user logs in and goes back to login page, user will get redirected dashboard
- Also placed style.css in the bottom of the head tags in adminSettings.php so admin's dashboard view is more aligned
> Added check to iepLogin.php

- adminInsert.php
- adminSettings.php
- userInsert.php
- userSettings.php
- Updated syntax and comments
- Name of the updated account is displayed when updated in admin settings.
- Admin settings scrolls up after updating account.
> Updated Setting Pages

- iepLogin.php
- Script that alerts user if user fails to login, redirects to the same page
> Added alert to iepLogin.php

- iepDocument.php
- style.css
Cleaned up code, changed document links to have underline and a different color
> Document styling updated

- style.css
messages appear in bottom of display
> Format message display
